### ISSUE TITLE
成员管理：新增成员/新增成员角色

### ISSUE THREAD

**Issue by MIAeh** [MIAeh/AchieveIt#10]
![image](https://user-images.githubusercontent.com/26197222/77827420-7dcb0180-7150-11ea-9c7f-7d9de51e03c1.png)

在“所有”tab中，新增成员不需要选择角色，直接加入“项目成员”列表
在角色组对应tab中，不需要选择角色，直接加入该tab的成员中

**Comment by MIAeh** [comment]
@vast00 @Jan-code 在对应tab中添加角色时，title需改成添加成员为{tab名称}角色，e.g. 添加成员为QA角色

**Comment by Jan-code** [comment]
<img width="539" alt="屏幕快照 2020-04-08 16 37 47" src="https://user-images.githubusercontent.com/27461837/78763146-60e7c700-79b7-11ea-8348-dfecd808034c.png">
