### ISSUE TITLE
登记工时记录：检查必填项

### ISSUE THREAD

**Issue by MIAeh** [MIAeh/AchieveIt#11]
![image](https://user-images.githubusercontent.com/26197222/77847511-19f81580-71f0-11ea-9dbe-3ccdbfcc64a0.png)
保存之前需要检查所有必填项，如有未填内容不允许创建/修改

**Comment by Jan-code** [comment]
<img width="646" alt="屏幕快照 2020-04-08 16 54 22" src="https://user-images.githubusercontent.com/27461837/78764806-a4dbcb80-79b9-11ea-8d09-fdff65f041ef.png">
