### ISSUE TITLE
登记工时记录：起止时间仅需时间段，Label名字勘误

### ISSUE THREAD

**Issue by MIAeh** [MIAeh/AchieveIt#12]
![image](https://user-images.githubusercontent.com/26197222/77847574-ad314b00-71f0-11ea-945f-92df9acbfe7b.png)

1. 日期以“申报日期”为准，起始时间仅需时间段（起、止需满足停止时间晚于开始时间的限制）
例如：起止时间：8.00-16.00

2. 此处”起始时间“应为”起止时间“

**Comment by Jan-code** [comment]
<img width="503" alt="屏幕快照 2020-04-08 16 44 06" src="https://user-images.githubusercontent.com/27461837/78763806-364a3e00-79b8-11ea-9c31-816830a3946d.png">
