### ISSUE TITLE
功能列表：新建功能隐藏“所属项目”

### ISSUE THREAD

**Issue by MIAeh** [MIAeh/AchieveIt#13]
![image](https://user-images.githubusercontent.com/26197222/77847619-216bee80-71f1-11ea-8470-f450e84e2a56.png)

**Comment by Jan-code** [comment]
<img width="688" alt="屏幕快照 2020-04-05 16 18 41" src="https://user-images.githubusercontent.com/27461837/78470080-24b72b00-7759-11ea-987f-249f413c9369.png">
 已隐藏
