### ISSUE TITLE
功能列表：功能ID返回顺序号

### ISSUE THREAD

**Issue by MIAeh** [MIAeh/AchieveIt#14]
![image](https://user-images.githubusercontent.com/26197222/77847645-4c564280-71f1-11ea-9fe3-e66e5286766a.png)
返回给前端顺序号而非UUID

**Comment by aleverys** [comment]
加入了FeatureDisplayID  前端可以用这个显示了

**Comment by aleverys** [comment]
加入了FeatureDisplayID  前端可以用这个显示了

**Comment by MIAeh** [comment]
@aleverys 前端反馈目前FeatureDisplayID返回数据为空

**Comment by aleverys** [comment]
去掉了FeatureDisplayID  重写了FeatureID生成算法 按照规则生成 已经不会再有UUID了
