### ISSUE TITLE
风险管理：风险列表展示信息

### ISSUE THREAD

**Issue by MIAeh** [MIAeh/AchieveIt#16]
![image](https://user-images.githubusercontent.com/26197222/77849488-824df380-71fe-11ea-8470-a0d2f8e6f025.png)

影响度展示的应该是“高/中/低”，状态应该由状态管理处理。
因此，应该在风险列表的“操作”栏中加入“确认解决”操作，执行后，风险状态从“处理中”变为“已解决”

**Comment by Jan-code** [comment]
<img width="1218" alt="屏幕快照 2020-04-05 14 42 01" src="https://user-images.githubusercontent.com/27461837/78468564-b91a9100-774b-11ea-8cfe-4c19ba2d02c0.png">

已改
