### ISSUE TITLE
权限管理：addFileMembersByID error500

### ISSUE THREAD

**Issue by MIAeh** [MIAeh/AchieveIt#19]
新增权限：文件服务器，执行后返回500错误，目前考虑问题为前端文件服务器权限误用了邮件管理数据，导致添加了重复成员

**Comment by MIAeh** [comment]
@Felix2048 检查一下后端逻辑

**Comment by Felix2048** [comment]
![image](https://user-images.githubusercontent.com/22152212/78918748-721dfa00-7ac3-11ea-966d-2700b7f3c22d.png)
后端应该是正常工作的，会不会是插入了不在成员里的User导致报错？

**Comment by MIAeh** [comment]
@vast00

**Comment by vast00** [comment]
![image](https://user-images.githubusercontent.com/34914392/78979141-ce2d6080-7b4d-11ea-983c-3ed24a62e070.png)
命令行中打印的是两次get的结果  删除请求前后两次get请求没变
@Felix2048 后端测试可以实际上网页开一下f12看一下请求

**Comment by Felix2048** [comment]
![image](https://user-images.githubusercontent.com/22152212/78981672-fcfa0580-7b52-11ea-96d5-c328f6060021.png)
已修复获取权限成员时的bug
