### ISSUE TITLE
状态管理：后台在项目表中存储归档链接

### ISSUE THREAD

**Issue by MIAeh** [MIAeh/AchieveIt#21]
项目经理提交归档链接后需存储在项目表中，如申请归档被驳回，则清空链接等待重新提交

**Comment by Felix2048** [comment]
![image](https://user-images.githubusercontent.com/22152212/78981880-7bef3e00-7b53-11ea-844b-92ea591cc9f8.png)

![image](https://user-images.githubusercontent.com/22152212/78981863-742f9980-7b53-11ea-888d-2376dcd9fb4f.png)

![image](https://user-images.githubusercontent.com/22152212/78981893-8578a600-7b53-11ea-81e9-3a311e1d7848.png)
