### ISSUE TITLE
新建项目：timeout error

### ISSUE THREAD

**Issue by MIAeh** [MIAeh/AchieveIt#29]
创建项目timeout error

**Comment by vast00** [comment]
这个接口前端传参有错误导致error，但是需要后端支持一下跨域post json的请求，否则前端没法测试 @Felix2048 @aleverys

**Comment by Felix2048** [comment]
- 已添加跨域Configuration，效果未知，待前端开发测试
- 已经移除创建项目和更新项目中的projectStatus，API已更新
- 已添加业务领域
- 待添加功能列表

**Comment by MIAeh** [comment]
@vast00

**Comment by vast00** [comment]
我这里本地跑还是接不通接口 一样的错误 @Felix2048
