### ISSUE TITLE
新建项目：需包含“业务领域”及“功能列表”（选填项）

### ISSUE THREAD

**Issue by MIAeh** [MIAeh/AchieveIt#3]
1. 业务领域为后台mock表，是一个下拉选择框
2. 功能列表应有createFeatureList接口（同步更新easyAPI）
两者为选填项，在创建时可不填

**Comment by Felix2048** [comment]
- 业务领域已添加
- 功能列表已添加，不过还存在bug @aleverys

**Comment by Felix2048** [comment]
通过Session获取当前用户（项目经理）ID存在问题，将在访问权限控制部分修复

**Comment by MIAeh** [comment]
@vast00 @Felix2048 待处理create timeout
@Jan-code postman测试通过的json文件需要修改 feature部分添加projectID
