### ISSUE TITLE
成员管理：删除成员

### ISSUE THREAD

**Issue by MIAeh** [MIAeh/AchieveIt#33]
1. 后端需要执行删除时的级联删除，包括：（优先级从上往下）
a.  移除权限列表中，该成员所有的权限
b. 删除该成员名下所有工时申报记录
c. 风险中，若该成员为责任人，责任人默认置为项目经理；若该成员为相关人，从相关人中移除
d. 被删除的成员的所有的下级成员的上级将设置为项目经理

2. 前端联通该接口

**Comment by Felix2048** [comment]
已完成：

-  移除权限列表中，该成员所有的权限
- 被删除的成员的所有的下级成员的上级将设置为项目经理

@aleverys ，TODO：

- 删除该成员名下所有工时申报记录
- 风险中，若该成员为责任人，责任人默认置为项目经理；若该成员为相关人，从相关人中移除
