### ISSUE TITLE
状态管理：前后端实现 VERY HIGH PRIORITY

### ISSUE THREAD

**Issue by MIAeh** [MIAeh/AchieveIt#37]

**Comment by Felix2048** [comment]
后端[接口API](https://www.easyapi.com/api/?documentId=25332&themeId=&categoryId=50246)已开发完成

**Comment by Felix2048** [comment]
TODO: 访问权限控制

**Comment by MIAeh** [comment]
@Jan-code @vast00 可推进

**Comment by MIAeh** [comment]
> TODO: 访问权限控制

https://github.com/MIAeh/AchieveIt/issues/39

**Comment by Jan-code** [comment]
前端完成
