### ISSUE TITLE
功能列表：删除功能需弹出确认dialog

### ISSUE THREAD

**Issue by MIAeh** [MIAeh/AchieveIt#60]
![image](https://user-images.githubusercontent.com/26197222/79086102-710ff580-7d6d-11ea-9b21-c5b4482f7090.png)
文本为：删除该功能时会同时删除其子功能，确认删除？

**Comment by Jan-code** [comment]
没有子功能的呢？

**Comment by MIAeh** [comment]
> 没有子功能的呢？

没有关系，用统一的alert text即可
